language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
services:
  - redis-server
install:
  - ./travisci-install.sh
before_script:
  - composer install
matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true
